const express = require('express')
const {getByName,getTeam, addengineer} = require('./controller/engineers')
const path = require('path')
const app = express()
app.set('view engine','pug')
app.use(express.static('public'))
app.use(express.json())
app.get('/theteam',express.json(),getTeam)
app.get('/theteam/:identifier', express.json(), getByName)
app.all('*', (req,res) => {
    return res.status(404)
})
app.listen(2026, () => {
    console.log('it is 2026')
})